FROM openjdk:8
VOLUME /tmp
ADD ./bin/logger-0.0.1-SNAPSHOT-jar-with-dependencies.jar logger-0.0.1-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java", "-jar", "logger-0.0.1-SNAPSHOT-jar-with-dependencies.jar"]
